name: bde
channels:
  - defaults
dependencies:
  - grpcio=1.42.0
  - grpcio-tools=1.42.0
  - notebook=6.5.4
  - pandas=1.5.3
  - pip=23.2.1
  - pyarrow=11.0.0
  - python=3.10
  - python-snappy=0.6.1
  - matplotlib=3.7.1
  - sqlalchemy=1.4.39
  - pip:
      - google-cloud-storage==2.10.0
      - pymongo==4.4.1
      - redis==4.6.0
      - thriftpy2==0.4.16
      - fastavro==1.8.2
      - requests==2.31.0
      - duckdb==0.8.1
      - duckdb-engine==0.9.2
