name: dwh
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.10.13
  - grpcio=1.48.2
  - pip:
      - dbt-bigquery==1.6.5
      - dagster==1.4.15
      - dagster-dbt==0.20.15
      - dagster-webserver==1.4.15
