name: elt
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
dependencies:
  - dbt-bigquery=1.9.1
  - dbt-core=1.9.6
  - great-expectations=1.4.1
  - matplotlib=3.10.0
  - pandas=2.1.4
  - pip=25.1
  - python=3.10.18
  - requests=2.32.3
  - pip:
      - meltano==3.7.8
prefix: /opt/miniconda3/envs/elt
